<a href="https://colab.research.google.com/github/arnavarya001/DATA-SCIENCE/blob/main/lect004ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

n = int(input("Enter number of products: "))

prices = np.array([
    int(input(f"Enter price of product {i+1}: "))
    for i in range(n)
])

print("Product Prices:", prices)

total = 0
maximum = prices[0]
minimum = prices[0]

for price in prices:
    total += price

    if price > maximum:
        maximum = price

    if price < minimum:
        minimum = price

print("Total Cart Value =", total)
print("Most Expensive Product =", maximum)
print("Cheapest Product =", minimum)

Enter number of products: 3
Enter price of product 1: 23
Enter price of product 2: 44
Enter price of product 3: 22
Product Prices: [23 44 22]
Total Cart Value = 89
Most Expensive Product = 44
Cheapest Product = 22


In [19]:
# Q1.
# create a 5*5 matrix of random integer(1-90)
# find mean values of row and column wise
# replace all even numbers with -1
# sort the array row and column wise
# find the row and colmun wise sum saparetly
# count the number of negatives in each column
import numpy as np

arr = np.random.randint(1,91,(5,5))
print(arr)

print("\nRow-wise Mean")
print(np.mean(arr,axis=1))

print("\nColumn-wise Mean")
print(np.mean(arr,axis=0))

arr = np.where(arr%2==0,-1,arr)
print("\nreplace even number with -1:")
print(arr)

rowSorted = np.sort(arr,axis=1)
print("\nsorted arrray row wise:")
print(rowSorted)

rowSorted = np.sort(arr,axis=0)
print("\nsorted arrray column wise:")
print(rowSorted)

print("\nrow-wise sum:")
print(np.sum(arr,axis=1))

print("\ncolumn-wise sum:")
print(np.sum(arr,axis=0))

# number of negative in each column"
count_col = np.sum(np.where(arr<0,1,0),axis=0)
print("\nnumber of negative in each column:")
print(count_col)

[[51 68 90 13 42]
 [ 4 73 57 55 41]
 [ 4 76 56 67 57]
 [90 28 24 44 32]
 [67 88 33 83 82]]

Row-wise Mean
[52.8 46.  52.  43.6 70.6]

Column-wise Mean
[43.2 66.6 52.  52.4 50.8]

replace even number with -1:
[[51 -1 -1 13 -1]
 [-1 73 57 55 41]
 [-1 -1 -1 67 57]
 [-1 -1 -1 -1 -1]
 [67 -1 33 83 -1]]

sorted arrray row wise:
[[-1 -1 -1 13 51]
 [-1 41 55 57 73]
 [-1 -1 -1 57 67]
 [-1 -1 -1 -1 -1]
 [-1 -1 33 67 83]]

sorted arrray column wise:
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 13 -1]
 [-1 -1 -1 55 -1]
 [51 -1 33 67 41]
 [67 73 57 83 57]]

row-wise sum:
[ 61 225 121  -5 181]

column-wise sum:
[115  69  87 217  95]

number of negative in each column:
[3 4 3 1 3]


In [30]:
# Q2.
# Inventory Control System

# Task:

# Create a 5*5 array(stock levels)
# Create another 5*5 array(demand)
# Compute:
# Remaining stock = stock - demand
# Replace:
# Negative values->0 (out of stock)
# Find:
# Totol shortage
# Products with zero stock
# Sort each row bassed on remaining stock

stock = np.random.randint(1,100,(5,5))
print("\nStock matrix")
print(stock)

demand = np.random.randint(1,100,(5,5))
print("\nDemand Matrix")
print(demand)

remaining = stock - demand
print("\nRemaining")
print(remaining)

remaining = np.where(remaining<0,0,remaining)
print("\nRemaining")
print(remaining)

total_shortage = np.sum(np.where(remaining<0,remaining*-1,0),axis=0)
print("\nTotal Shortage")
print(total_shortage)

zero_stock = np.sum(np.where(remaining==0,1,0),axis=0)
print("\nProducts with zero stock")
print(zero_stock)

sorted_remaining = np.sort(remaining,axis=1)
print("\nSorted Remaining")
print(sorted_remaining)







Stock matrix
[[95 88 79 28 78]
 [57  7 60 15 52]
 [59 58 72 51  2]
 [52  9 96 82 86]
 [11 32 78 67 62]]

Demand Matrix
[[67 90 29 93 43]
 [17 26 34 74  8]
 [18 87 28 31 34]
 [ 5 83  3  5  4]
 [ 6 53 61 63 48]]

Remaining
[[ 28  -2  50 -65  35]
 [ 40 -19  26 -59  44]
 [ 41 -29  44  20 -32]
 [ 47 -74  93  77  82]
 [  5 -21  17   4  14]]

Remaining
[[28  0 50  0 35]
 [40  0 26  0 44]
 [41  0 44 20  0]
 [47  0 93 77 82]
 [ 5  0 17  4 14]]

Total Shortage
[0 0 0 0 0]

Products with zero stock
[0 5 0 2 1]

Sorted Remaining
[[ 0  0 28 35 50]
 [ 0  0 26 40 44]
 [ 0  0 20 41 44]
 [ 0 47 77 82 93]
 [ 0  4  5 14 17]]


Pandas

In [38]:
import pandas as pd

file = pd.read_csv("./student_data.csv",sep=",")
print(file.head())



   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   
5            7          40            9              10   
6           10          40            4              11   
7            3          86            7               3   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  
5                      0            