<a href="https://colab.research.google.com/github/arnavarya001/DATA-SCIENCE/blob/main/lect003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [166]:
import numpy as np

In [167]:
import numpy as np

arr = np.array([1, 2, 3, 4, '33'])
print(arr)

['1' '2' '3' '4' '33']


In [168]:
np_arr = np.array([3,3,3,33.3,'heloo',False])
print(bool(np_arr[-1]))
# non empty string is true
a = False
print(bool(a))

True
False


Numpy function

In [169]:
# a = np.zeros((row,row,column))
a = np.zeros((2,3,4),dtype=int)
print(a)
print(type(a))
print(type(a[0][0][0]))


[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [170]:
a = np.ones((2,3,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [171]:
a = np.empty(4,dtype=int)
print(a)

[2 2 6 2]


In [172]:
a = np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [173]:
# np.arange(start,stop,step)
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [174]:
# np.linspace(start,stop,number of value)
a = np.linspace(1,9,5)
print(a)

[1. 3. 5. 7. 9.]


In [175]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

(2, 3)


In [176]:
arr = np.shape([[1, 2, 3],[4, 5, 6],[3,3,2]])
print(arr)


(3, 3)


In [177]:
arr = np.size([[1, 2, 3],[4, 5, 6],[3,3,2]])
print(arr)


9


In [178]:
arr = np.random.randint([[1, 2, 3],[4, 5, 6],[3,3,2]])
arr1 = np.random.randint(1,7,4)

print(arr)

print(arr1)


[[0 1 0]
 [0 4 1]
 [1 0 0]]
[3 6 5 4]


In [179]:
arr = np.random.choice([2,43,5,6,5])
arr1 = np.random.choice([2,34,5,33,2],4)
arr2 = np.random.choice(4)

print(arr)
print(arr1)
print(arr2)



5
[2 2 5 2]
0


In [180]:

# Arrray
arr = np.array([23,4,45,67,7])

print(arr * 2)
print(arr + 2)
print(arr - 2)
print(arr / 2)

[ 46   8  90 134  14]
[25  6 47 69  9]
[21  2 43 65  5]
[11.5  2.  22.5 33.5  3.5]


In [181]:
# list
arr = [23, 4, 45, 67, 7]

print([arr * 2])
# print([arr + 2])
# print([arr - 2])
# print([arr / 2])

[[23, 4, 45, 67, 7, 23, 4, 45, 67, 7]]


In [182]:
a = np.random.randint(2,40,6)
print(a)
b = a.reshape((3,2))
print(b)

[19  5 29  5 17 33]
[[19  5]
 [29  5]
 [17 33]]


In [183]:
a = np.random.randint(2,40,6)
print(a)
b = a.transpose()
print(b)

[11 24  2 36  2 38]
[11 24  2 36  2 38]


In [184]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])

print("Original Array:")
print(a)

Original Array:
[[10 20 30]
 [40 50 60]]


In [185]:
a = np.random.randint(2,40,6)
b = np.random.randint(1,19,6)

print(np.concatenate((a, b), axis=0))

[32 33  4 26 37 24  7  8 11 14 13  6]


In [186]:
# a = np.array([[10, 20, 30],
#               [40, 50, 60]])
a = np.random.randint(2,40,6)
b = np.random.randint(1,19,6)
print(a)
print(b)
# b = np.where(condition,x,y))
c = np.where(a > 4,b,a)
print(c)

[ 8 11 34 13  3 20]
[ 3 17  9 15  7  4]
[ 3 17  9 15  3  4]


In [187]:

c = np.array([30, 10, 50, 20, 40])

print(np.sort(c))

[10 20 30 40 50]


In [188]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print(np.sum(a))

210


In [189]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(np.mean(a))

35.0


In [190]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print(np.std(a))

17.07825127659933


In [191]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print(np.min(a))

10


In [192]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print(np.max(a))

60


In [193]:
d = np.array([10, 20, 20, 30, 30, 40])

print(np.unique(d))

[10 20 30 40]


In [194]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print(a.shape)

(2, 3)


In [195]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print(a.size)

6


In [196]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print(a.dtype)

int64


In [209]:
a = np.random.randint(2,18,4)
print(a)
print(sum(a))
print(max(a))
print(min(a))





[11  8  2  6]
27
11
2


In [218]:
n = int(input("Enter number of scores: "))
score = np.array([int(input("Enter score: "))
for i in range(n)])
print("Scores:", score)
total = 0
maximum = score[0]
minimum = score[0]

for i in score:
    total += i
    if i > maximum:
        maximum = i
    if i < minimum:
        minimum = i

print("Sum =", total)
print("Max =", maximum)
print("Min =", minimum)

Enter number of scores: 3
Enter score: 1
Enter score: 3
Enter score: 2
Scores: [1 3 2]
Sum = 6
Max = 3
Min = 1


In [ ]:
import numpy as np

days = ["Monday", "Tuesday", "Wednesday",
        "Thursday", "Friday", "Saturday", "Sunday"]

scores = []

for day in days:
    s = int(input(f"Enter score for {day}: "))
    scores.append(s)

scores = np.array(scores)

print("\nScores:")
for i in range(len(days)):
    print(days[i], ":", scores[i])

max_score = scores[0]
min_score = scores[0]
max_day = days[0]
min_day = days[0]

for i in range(len(scores)):
    if scores[i] > max_score:
        max_score = scores[i]
        max_day = days[i]

    if scores[i] < min_score:
        min_score = scores[i]
        min_day = days[i]

print("\nHighest Score:", max_score, "on", max_day)
print("Lowest Score:", min_score, "on", min_day)

In [226]:
# scores = []
scores = input().split()
print(scores)

scores = [int(x) for x in scores]
print(scores)
# days = ["Monday", "Tuesday", "Wednesday",
#         "Thursday", "Friday", "Saturday", "Sunday"]
# for i in range(7):
#   x = input(f'give the input for the {days[i]}:')


3 4 5 6
['3', '4', '5', '6']
[3, 4, 5, 6]
